GET http://88.200.63.148:4445/users

###

POST http://88.200.63.148:4445/users
Content-Type: application/json
{
    "ime": "Stanko",
    "priimek": "Stankovski",
    "email": "stanko@example.com",
    "geslo": "password123",
    "vloga": "navaden"
}