GET process.env.REACT_APP_API_URL/users

###

POST process.env.REACT_APP_API_URL/users
Content-Type: application/json
{
    "ime": "Stanko",
    "priimek": "Stankovski",
    "email": "stanko@example.com",
    "geslo": "password123",
    "vloga": "navaden"
}