import React from 'react';
import './AboutProject.css';

const descriptions = {
  mk: `Традиционалните македонски народни ора се загрозени поради недостаток на централизирана, интерактивна и достапна платформа за нивно документирање, учење и ширење. Постоечките извори се фрагментирани, неинтерактивни и не ги вклучуваат младите генерации или глобалните ентузијасти. Овој проблем се јавува во културните институции, фолклорните групи, образовните центри и кај поединци кои се обидуваат да ги зачуваат и пренесат овие традиции. Недостасува модерна платформа која ги обединува историските податоци, мултимедијалните извори и можностите за заедница. Овие фактори водат до губење на културното наследство и ограничен пристап до учење. Ова негативно влијае на институциите и групите кои се соочуваат со потешкотии при систематско архивирање и промоција на ората, како и на учителите и кореографите кои немаат ефективни интерактивни алатки за подучување на чекори и техники. Студентите и ентузијастите се ограничени во самостојното учење или посетување на фолклорни групи поради недостиг на достапни извори и можности за поврзување, додека туристите и истражувачите немаат централизирани информации за регионалните варијации и историското значење на ората. Сето ова ја загрозува одржливоста и глобалниот досег на македонското оро. Проблемот е недостаток на дигитална инфраструктура за зачувување на македонскиот народен танц, што влијае на културниот идентитет и образованието. Иако постојат физички архиви и локални иницијативи, тие не се прилагодени на современите дигитални потреби и глобалниот досег. Затоа, целта е да се развие дигитална платформа која ќе го реши недостатокот на инфраструктура за зачувување на македонското оро. Платформата ќе ги поврзе традиционалните знаења со современите технологии, ќе овозможи пристап за пошироката глобална заедница, ќе поддржува повеќе јазици и ќе служи како едукативна алатка за училишта и фолклорни групи, како и извор за туристи и истражувачи кои сакаат подлабоко да ја разберат македонската културна идентитет.`,
  en: `Traditional Macedonian folk dances (ora) are endangered due to the lack of a centralized, interactive, and accessible system for their documentation, learning, and dissemination. Existing resources are fragmented, non-interactive, and do not engage younger generations or global enthusiasts. This problem affects cultural institutions, dance groups, educational centers, and individuals striving to preserve and transmit these traditions. There is a lack of a modern platform that unites historical data, multimedia resources, and community features. These factors lead to the loss of cultural heritage and limited access to learning. This negatively impacts cultural institutions and dance groups, which face difficulties in systematic archiving and promotion, as well as teachers and choreographers who lack effective interactive tools for teaching dance steps and techniques. Students and enthusiasts are limited in self-learning or joining folklore groups due to the lack of accessible resources and opportunities to connect with dance communities, while tourists and researchers miss centralized information about regional dance variations and their historical significance. All these factors threaten the sustainability and global reach of dance heritage. The problem is the lack of digital infrastructure for preserving Macedonian folk dance, which affects cultural identity and education. Despite existing physical archives and local initiatives, these are not adapted to modern digital needs and global reach. Therefore, the goal is to develop a digital platform that will address the lack of infrastructure for preserving Macedonian folk dance. The platform will connect traditional knowledge with modern technologies, enable access for a wider global community, support multilingualism, and serve as an educational tool for schools and dance groups, as well as a resource for tourists and researchers seeking a deeper understanding of Macedonian cultural identity.`,
  si: `Tradicionalni makedonski ljudski plesi (ora) so ogroženi zaradi pomanjkanja centraliziranega, interaktivnega in dostopnega sistema za njihovo dokumentiranje, učenje ter širjenje. Obstoječi viri so razdrobljeni, neinteraktivni in ne vključujejo mlajših generacij ali globalnih navdušencev. Problem se pojavlja v kulturnih institucijah, plesnih skupinah, izobraževalnih centrih in med posamezniki, ki poskušajo ohraniti in prenašati te tradicije. Manjka moderna platforma, ki bi združevala zgodovinske podatke, multimedijske vire in skupnostne možnosti. Ti dejavniki vodijo do izgube kulturne dediščine in omejenega dostopa do učenja. To negativno vpliva na kulturne institucije in plesne skupine, ki se soočajo s težavami pri sistematičnem arhiviranju in promociji plesov, ter učitelje oziroma koreografe, ki ne morejo učinkovito poučevati plesnih korakov in tehnik, saj jim primanjkuje interaktivnih orodij. Študenti in navdušenci so omejeni pri samostojnem učenju ali obiskovanju folklornih skupin zaradi pomanjkanja dostopnih virov in možnosti povezovanja s plesnimi skupnostmi, medtem ko turisti in raziskovalci pogrešajo centralizirane informacije o regionalnih različicah plesov in njihovi zgodovinski pomembnosti. Vsi ti dejavniki skupaj ogrožajo trajnost plesne dediščine in njen globalni doseg. Problem zajema pomanjkanje digitalne infrastrukture za ohranjanje makedonskega ljudskega plesa, kar vpliva na kulturno identiteto in izobraževanje. Kljub obstoječim fizičnim arhivom in lokalnim pobudam ti niso prilagojeni sodobnim digitalnim potrebam in globalnemu dosegu. Za ta namen želimo razviti digitalno platformo, ki bo rešila pomanjkanje infrastrukture za ohranjanje makedonskega ljudskega plesa. Platforma naj bi povezala tradicionalno znanje s sodobnimi tehnologijami, omogočila dostop širši globalni skupnosti, kar bi lahko vključilo podporo z strani jezika/večjezičnosti, in bi služila kot izobraževalno orodje za šole in plesne skupine ter kot vir za turiste in raziskovalce, ki želijo globlje razumeti makedonsko kulturno identiteto.`
};

export default function AboutProject() {
  
  return (
    <div className="about-project">
      <h2>About the Project / За проектот / O projektu</h2>
      <section>
        <h3>Македонски</h3>
        <p>{descriptions.mk}</p>
      </section>
      <section>
        <h3>English</h3>
        <p>{descriptions.en}</p>
      </section>
      <section>
        <h3>Slovenščina</h3>
        <p>{descriptions.si}</p>
      </section>
    </div>
  );
}
